### ISSUE TITLE
Automating adding of new speakers

### ISSUE THREAD

**Issue by blackunicorn47** [ppwwyyxx/speaker-recognition#39] opened 2017-05-31 05:59 UTC
Can it be possible to add a 10-15 min audio clip of 4-5 people conversing and it recognizes different voices in the audio clip without a sample voice clip of each person ?
Figuring out the voices without a separate sample of each voice in the 10-15 min audio clip.

**Comment by ppwwyyxx** [comment] 2017-05-31 06:10
It cannot.

**Comment by blackunicorn47** [comment] 2017-05-31 06:21
Is it possible for someone to add some changes to this and make it possible ?
And sorry for for sounding stupid, but has machine learning been implemented on this project ?

**Comment by ppwwyyxx** [comment] 2017-05-31 06:44
Maybe. It won't be easy.

Yes. There is machine learning.

**Comment by blackunicorn47** [comment] 2017-05-31 06:57
Hi Yuxin,

First of all this congrats for making such an awesome project !!

Now, I am a college student who has sound knowledge of python but no
experience and in machine learning. So what I said about implementing the
automatic detection of speakers, would it be possible for me (someone with
no experience in machine learning) with the skillset I just mentioned ?

**Comment by ppwwyyxx** [comment] 2017-05-31 07:29
It's certainly not impossible, but from what I know what you described is a very hard problem in machine learning.

**Comment by blackunicorn47** [comment] 2017-05-31 07:32
any leads on how to proceed ?

**Comment by ppwwyyxx** [comment] 2017-05-31 07:50
I don't have any reasonable ideas on this.

**Comment by blackunicorn47** [comment] 2017-06-01 06:31
The src/gui/gui.py file was working fine up until yesterday but now every time I upload a sound clip for training in .wav (mono) file format and click on enroll 

Enroll: 0.0000 seconds
Error! Input is silent! Please enroll again
is being shown and voices are also not being trained. 



And also speaker-recognition.py on running shows --

Warning: failed to import Bob, will use a slower version of MFCC instead.
Warning: failed to import fast-gmm, use gmm from scikit-learn instead
usage: speaker-recognition.py [-h] -t TASK -i INPUT -m MODEL
speaker-recognition.py: error: argument -t/--task is required

Process finished with exit code 2


What could be the problem ?

**Comment by ppwwyyxx** [comment] 2017-06-01 06:55
GUI thinks your wav has no voices. I don't know why. If it worked before please try with a wav file working before.

The command line util expects options. Please see the README.

**Comment by blackunicorn47** [comment] 2017-06-05 06:31
Right now I need to train this with the voices or load the dump every time I run this program. Is there a way that all the user voice is stored once without having the need to train/upload the dump again ?

**Comment by ppwwyyxx** [comment] 2017-06-05 07:22
no such feature

**Comment by blackunicorn47** [comment] 2017-06-06 12:00
Lately training is taking too long (~ 25 minutes in some cases) for audio clips of 1-2 minutes. What could be causing this ?

**Comment by blackunicorn47** [comment] 2017-06-08 10:35
`Start training...
training from ubm ...
nr_instance   :   5112
nr_dim        :   28
nr_mixture    :   32
min_covar     :   0.001000
threshold     :   0.010000
nr_iteration  :   200
init_with_kmeans: 0
concurrency   :   4
verbosity     :   0
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`


What could be done to solve this problem ?
This is happening when training the voice sample

**Comment by blackunicorn47** [comment] 2017-06-08 10:37
`
Start training... training from ubm ... nr_instance : 5112 nr_dim : 28 nr_mixture : 32 min_covar : 0.001000 threshold : 0.010000 nr_iteration : 200 init_with_kmeans: 0 concurrency : 4 verbosity : 0 python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector&, double*): Assertion (int)x.size() == dim' failed. python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion(int)x.size() == dim' failed.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`
`

What could be done to solve this problem ?
This is happening when training the voice sample

**Comment by blackunicorn47** [comment] 2017-06-08 10:40
`python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion ``(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion ``(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion ``(int)x.size() == dim' failed.`

What could be done to solve this problem ?
This is happening when training the voice sample`

**Comment by blackunicorn47** [comment] 2017-06-08 10:41
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed. python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed. python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.

What could be done to solve this problem ?
This is happening when training the voice sample`

**Comment by blackunicorn47** [comment] 2017-06-08 10:42
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
python2.7: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.

What could be done to solve this problem ?
This is happening when training the voice sample`

**Comment by qacollective** [comment] 2017-06-08 12:29
@blackunicorn47 
This is possibly a duplicate of #34 and #32.  Read those for some details.

Also, I'm not sure if you and I are trying to achieve the same thing, but I do have an idea that may work in using this project to solve problems of this nature.  I came to this site today to run my thinking past @ppwwyyxx , so I will do that in another issue.

**Comment by blackunicorn47** [comment] 2017-07-07 09:55
How can I use the conversation mode to run an audio file instead of using the computer's speaker for live audio ?

**Closed** 2017-08-19 05:10 UTC
