### ISSUE TITLE
Not working when UBM is used

### ISSUE THREAD

**Issue by pankajksharma** [ppwwyyxx/speaker-recognition#34] opened 2017-05-09 13:54 UTC
After UBM is loaded, enroll task gives following error:
python2: src/gmm.cc:177: real_t Gaussian::probability_of_fast_exp(std::vector<double>&, double*): Assertion `(int)x.size() == dim' failed.
Aborted (core dumped)

gmm_order=32
UBM_MODEL_FILE = 'gui/model/ubm.mixture-32.utt-300.model'

**Comment by ppwwyyxx** [comment] 2017-05-09 14:18
duplicate of #32

**Closed** 2017-05-22 15:52 UTC
