### ISSUE TITLE
Please add requirements.txt and some guide how to start it

### ISSUE THREAD

**Issue by DenisSouth** [ppwwyyxx/speaker-recognition#82] opened 2018-12-09 18:35 UTC
Hello. Please add any instruction how to start this project,, requirements.txt   and some paper about algorithm and accuracy of its result
I really need any project with score >80%. I tried your project many times on Ubuntu 16/18 , Debian, Windows XP/7/8/10 with python 2.7/3.6 nothing works. 
I got one more  useless protect with huge number of stars

**Comment by ppwwyyxx** [comment] 2018-12-09 18:52
Adding "requirements.txt" is a duplicate of #77.

The project was successfully used by many people. The most recent success report was only two days ago (#81). If you meet any issues, please report a bug, including what you did, what you observed, and what you expected. Complaining is not helpful to anyone.

**Closed by ppwwyyxx** 2018-12-09 18:52 UTC

**Comment by DenisSouth** [comment] 2018-12-09 21:14
ok, please tell me which python version I need for this project

**Comment by ppwwyyxx** [comment] 2018-12-09 21:48
Python 2.7
